"""Bazalt — Python library for rapid GPU shader prototyping using Vulkan."""

from bazalt._core import *  # noqa: F401, F403
from bazalt._core import (  # noqa: F401 — explicit re-exports for IDE visibility
    Context,
    RenderTarget,
    RenderTargetBase,
    SwapchainRenderer,
    Window,
    Logger,
    LogMessage,
    Buffer,
    ShaderModule,
    Texture,
    Pipeline,
    PipelineBuilder,
    DescriptorPool,
    DescriptorSet,
    CommandBuffer,
    MouseState,
    BufferType,
    DataType,
    ShaderStage,
    VertexFormat,
    CullMode,
    FrontFace,
    MemoryUsage,
    Severity,
    Source,
    Feature,
    BazaltError,
    InitializationError,
    DeviceLostError,
    OutOfMemoryError,
    ShaderError,
    WindowError,
    ResourceError,
)

__version__ = "0.4.2"

__all__ = [
    # Core
    "Context",
    "RenderTarget",
    "RenderTargetBase",
    "SwapchainRenderer",
    "Window",
    "Logger",
    "LogMessage",
    # Resources
    "Buffer",
    "ShaderModule",
    "Texture",
    "Pipeline",
    "PipelineBuilder",
    "DescriptorPool",
    "DescriptorSet",
    "CommandBuffer",
    # Data types
    "MouseState",
    "BufferType",
    "DataType",
    "ShaderStage",
    "VertexFormat",
    "CullMode",
    "FrontFace",
    "MemoryUsage",
    "Severity",
    "Source",
    "Feature",
    # Errors — the type is the recoverability contract
    "BazaltError",
    "InitializationError",
    "DeviceLostError",
    "OutOfMemoryError",
    "ShaderError",
    "WindowError",
    "ResourceError",
    # Version
    "__version__",
]
